### ISSUE TITLE
Failed step "success" of plugin "@semantic-release/github"

### ISSUE THREAD

**Issue by cmani97** [thecodinganalyst/semantic-java#2]
Everything is working fine but at the last step, my release failed. See the error below
```
[8:09:35 AM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/github"
[8:09:35 AM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/github"
[8:09:45 AM] [semantic-release] › ✖  Failed step "success" of plugin "@semantic-release/github"
[8:09:45 AM] [semantic-release] › ✖  An error occurred while running semantic-release: RequestError [HttpError]: Validation Failed: {"message":"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.","resource":"Search","field":"q","code":"invalid"}
    at /opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/semantic-release/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 422,
  response: {
    url: 'https://api.github.com/search/issues?q=repo%3Acmani97%2Fsemantic-java+type%3Apr+is%3Amerged+a357d3f6e31770590fe1a6e8868e1d246198b437',
    status: 422,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'cache-control': 'no-cache',
      connection: 'close',
      'content-length': '301',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Thu, 27 Jan 2022 08:09:45 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept, Authorization, Cookie, X-GitHub-OTP, Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '0400:6ACE:1A4A4E9:4137E56:61F25348',
      'x-ratelimit-limit': '30',
      'x-ratelimit-remaining': '26',
      'x-ratelimit-reset': '1643271037',
      'x-ratelimit-resource': 'search',
      'x-ratelimit-used': '4',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Validation Failed',
      errors: [Array],
      documentation_url: 'https://docs.github.com/v3/search/'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/search/issues?q=repo%3Acmani97%2Fsemantic-java+type%3Apr+is%3Amerged+a357d3f6e31770590fe1a6e8868e1d246198b437',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.12.0 octokit-core.js/3.5.1 Node.js/16.13.2 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { agent: undefined, hook: [Function: bound bound register] }
  },
  attemptNumber: 4,
  retriesLeft: 0,
  pluginName: '@semantic-release/github'
}
AggregateError: 
    HttpError: Validation Failed: {"message":"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.","resource":"Search","field":"q","code":"invalid"}
        at /opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/semantic-release/node_modules/@octokit/request/dist-node/index.js:86:21
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at async Object.pluginsConf.<computed> [as success] (/opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/semantic-release/index.js:209:3)
    at async module.exports (/opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/semantic-release/index.js:268:22)
    at async module.exports (/opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/semantic-release/cli.js:55:5)
Error: Process completed with exit code 1.
```
What went wrong?

**Comment by thecodinganalyst** [comment]
did you change the value of repositoryUrl to your own repo? U can refer to https://thecodinganalyst.github.io/knowledgebase/Basic-guide-to-Semantic-Release/ to understand how it works

**Comment by cmani97** [comment]
Yes, I followed the same process, and here is my `.releaserc` file 
```
{
  "branches": [
    "master",
     { name: "beta", prerelease: true }
  ],
  "repositoryUrl": "https://github.com/cmani97/semantic-java",
  "debug": "false",
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/changelog",
      {
        "changelogFile": "CHANGELOG.md",
        "changelogTitle": "# Semantic Versioning Changelog"
      }
    ],
    [
      "@semantic-release/git",
      {
        "assets": ["CHANGELOG.md"]
      }
    ],
    [
      "@semantic-release/github",
      {
        "assets": [
          {
            "path": "release/**"
          }
        ]
      }
    ]
  ]
}
```

**Comment by thecodinganalyst** [comment]
From the error message you got, it mentions "The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them." So this is apparently a permission issue.

1. Did you set up the GH_TOKEN in the Secrets?
2. If so, does your GH_TOKEN has access to your private repository? From the repositoryUrl you provided, I can't see the repository.

**Comment by cmani97** [comment]
I changed the repo private to the public now it's working fine. But it's only releasing the tags not packages of related versions.
I even tried using the below action
```
      - name: Publish to GitHub Packages  Apache Maven
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
it creating the package like below
```
<dependency>
  <groupId>org.example</groupId>
  <artifactId>semantic-java</artifactId>
  <version>1.0.0</version>
</dependency>
```
but I need a package based on the latest release like below
```
<dependency>
  <groupId>org.example</groupId>
  <artifactId>semantic-java</artifactId>
  <version>1.0.3-beta.3</version>
</dependency>

**Comment by cmani97** [comment]
How to apply this for private repositories. Could you please tell me? I have tried but no use.
without semantic version for the private repo `GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}` worked fine. But after adding a semantic version to the GitHub action it is not working.
